In [1]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\15442\appdata\roaming\python\python310\site-packages (1.4.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\15442\appdata\roaming\python\python310\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\15442\appdata\roaming\python\python310\site-packages (from pandas) (1.23.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\15442\appdata\roaming\python\python310\site-packages (from pandas) (2022.2.1)
Requirement already satisfied: six>=1.5 in c:\users\15442\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('C:\\Users\\15442\\Desktop\\Files\\ETL\\Sales_Team_Leader.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3436397 entries, 0 to 3436396
Data columns (total 10 columns):
 #   Column                    Dtype
---  ------                    -----
 0   TEAM_LEADER               object
 1   TEAM_LEADER_JOINING_DATE  object
 2   TEAM_LEADER_LEAVE_DATE    object
 3   KEC                       object
 4   KEC_NAME                  object
 5   KEC_CODE                  object
 6   KEC_JOIN_DATE             object
 7   KEC_LEAVE_DATE            object
 8   EQRY_ENQRY_NO             object
 9   EQRY_DLR_NO               object
dtypes: object(10)
memory usage: 262.2+ MB

In [5]:
df.shape

(3436397, 10)

In [6]:
df.isna().sum()

TEAM_LEADER                 1149841
TEAM_LEADER_JOINING_DATE    1149841
TEAM_LEADER_LEAVE_DATE      3425486
KEC                            7367
KEC_NAME                       7445
KEC_CODE                          0
KEC_JOIN_DATE                  7449
KEC_LEAVE_DATE              2405469
EQRY_ENQRY_NO                     0
EQRY_DLR_NO                       0
dtype: int64

In [7]:
df

,TEAM_LEADER,TEAM_LEADER_JOINING_DATE,TEAM_LEADER_LEAVE_DATE,KEC,KEC_NAME,KEC_CODE,KEC_JOIN_DATE,KEC_LEAVE_DATE,EQRY_ENQRY_NO,EQRY_DLR_NO
0,NaN,NaN,NaN,EAP3020001,Aditya Soni,TRAP30220190001,2019-07-14,NaN,E201900003,TRAP302
1,NaN,NaN,NaN,EUP4030004,KASHISH SHARMA,TRUP40320190004,2019-07-10,1970-01-01 00:00:00.020210817,E201900001,TRUP403
2,EUP4030014;VISHAL SHARMA;Active,2019-07-14,NaN,EUP4030002,HIMANSHU MITTAL,TRUP40320190002,2019-07-10,NaN,E201900003,TRUP403
3,NaN,NaN,NaN,EUP4030001,RANJANA SAXENA,TRUP40320190001,2019-07-10,NaN,E201900006,TRUP403
4,NaN,NaN,NaN,EUP4030001,RANJANA SAXENA,TRUP40320190001,2019-07-10,NaN,E201900007,TRUP403
...,...,...,...,...,...,...,...,...,...,...
3436392,NaN,NaN,NaN,EKA5020055,MUSTAFA S MULLA,TRKA50220210030,2021-09-14,NaN,E202201318,TRKA502
3436393,ERJ3020004;Mohit Sharma;Active,2021-02-11,NaN,ERJ3020012,REKHA JAIN,TRRJ30220210003,2021-02-11,NaN,E202205715,TRRJ302
3436394,EPB1010017;RAJBIR SINGH;Active,2019-10-11,NaN,EPB1010034,ANKUR SETHI,TRPB10120200012,2020-02-22,NaN,E202203370,TRPB101
3436395,EMH4100076;LAXMIKANT RAMSIRJAN PANDEY;Active,2020-08-18,NaN,EMH4100089,RAVIKANT RAJESH MISHRA,TR,2020-11-10,NaN,E202207685,TRMH410
3436396,EMH4050061;Amol Chandrakant Chavan;Active,2020-08-01,NaN,EMH4050029,Reshma Pralhad Channe,TRMH40520190006,2019-12-20,NaN,E202207084,TRMH405

In [8]:
df['TEAM_LEADER']

0                                                   NaN
1                                                   NaN
2                       EUP4030014;VISHAL SHARMA;Active
3                                                   NaN
4                                                   NaN
                               ...
3436392                                             NaN
3436393                  ERJ3020004;Mohit Sharma;Active
3436394                  EPB1010017;RAJBIR SINGH;Active
3436395    EMH4100076;LAXMIKANT RAMSIRJAN PANDEY;Active
3436396       EMH4050061;Amol Chandrakant Chavan;Active
Name: TEAM_LEADER, Length: 3436397, dtype: object

In [9]:
# for i in df['TEAM_LEADER']:
#     if i != 'nan':
#         print(f"{i} ----------------------- {type(i)}")

In [10]:
df['TEAM_LEADER'] = df["TEAM_LEADER"].map(str)

In [11]:
# for i in df['TEAM_LEADER']:
# #     if i != 'nan':
#         print(f"{i} ----------------------- {type(i)}")

In [12]:
Team_Leader_Code = []
Team_Leader_Name = []
Active_Inactive = []

In [13]:
for i in df['TEAM_LEADER']:
    x = i.split(';')
    y = x[0]
    Team_Leader_Code.append(y)

In [14]:
Team_Leader_Code

['nan',
 'nan',
 'EUP4030014',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EKA4050088',
 'EKA4050052',
 'nan',
 'nan',
 'ETS4030013',
 'ETS4010260',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EWB4020097',
 'nan',
 'nan',
 'EMH3020049',
 'EKA4050200',
 'ERJ4030107',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH3020049',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH3020049',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EKL3040014',
 'nan',
 'nan',
 'EMH3020049',
 'EKA4050052',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EGJ3040104',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH4010017',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH3020049',
 'nan',
 'nan',
 'EDL4040133',
 'nan',
 'nan',
 'ERJ4030107',
 'nan',
 'nan',
 'EGJ3040104',
 'nan',
 'ERJ4020001',
 'ERJ4030107',
 'nan',
 'EWB4020013',
 'ECG3010015',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EGJ3060001',
 'nan',
 'EUP3010006',
 'nan',
 'nan',
 'EGJ3040104',
 'ERJ4030010',
 'EPB3010009',
 'nan',
 'EUP3010006',
 'EPB3020012',
 'nan',
 'ERJ4030107',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EOD3010080',
 'nan',
 'EUP3040115',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EOD3010080',
 'nan',
 'nan',
 'nan',
 'EOD3010131',
 'nan',
 'nan',
 'EOD3010080',
 'ERJ4010003',
 'nan',
 'EMH3020049',
 'nan',
 'EUP3010006',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EAP3040004',
 'nan',
 'nan',
 'nan',
 'EUP3010006',
 'ERJ4010106',
 'nan',
 'EHR3010002',
 'nan',
 'EDL4040133',
 'nan',
 'nan',
 'nan',
 'nan',
 'EKA4050088',
 'EKA4050088',
 'EKA4050088',
 'nan',
 'nan',
 'nan',
 'EKA4050052',
 'EKA4050052',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ERJ4010106',
 'ERJ4030107',
 'nan',
 'nan',
 'nan',
 'nan',
 'EKL3030062',
 'nan',
 'EKL3030062',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EPB3010020',
 'nan',
 'EGJ1010003',
 'EGJ3050064',
 'EGJ4010021',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EKA4050088',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH3020049',
 'EKA4050052',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EDL3010251',
 'nan',
 'ERJ4030107',
 'EUP3070151',
 'ERJ4030107',
 'EKA4050052',
 'nan',
 'EKL3040014',
 'nan',
 'EGJ3040104',
 'nan',
 'EOD3010131',
 'EKL3030062',
 'nan',
 'EGJ3050016',
 'EKL3030062',
 'nan',
 'nan',
 'nan',
 'EAP3040007',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EDL3010251',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EKA4010122',
 'nan',
 'nan',
 'EMH4010008',
 'nan',
 'EPB3010003',
 'EMP3010091',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EUP4030014',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EUP3040004',
 'EUP3040004',
 'EWB4020015',
 'nan',
 'EKA4030035',
 'nan',
 'EHR4010061',
 'EKA4010122',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EUP4030014',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EAS4010012',
 'EMP3010112',
 'nan',
 'nan',
 'ETN3060030',
 'EHR4050069',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ETS4030013',
 'ETN4010141',
 'nan',
 'ETS4030013',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH1040013',
 'nan',
 'nan',
 'ETS4030013',
 'nan',
 'nan',
 'nan',
 'EAP3040007',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EKA4010118',
 'EMH4010008',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EAP3040004',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH1040013',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EKA4010122',
 'nan',
 'nan',
 'nan',
 'ETS4010260',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EUP3040115',
 'EMH1040057',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EKA4050088',
 'nan',
 'EAP4030016',
 'EKL3030062',
 'nan',
 'nan',
 'EMH4010017',
 'nan',
 'EMH4010008',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH3020049',
 'nan',
 'EAS4010012',
 'nan',
 'nan',
 'nan',
 'nan',
 'EWB4020015',
 'EMH3020049',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EAS4010012',
 'nan',
 'nan',
 'nan',
 'nan',
 'EWB4020015',
 'nan',
 'nan',
 'nan',
 'EOD3010080',
 'nan',
 'nan',
 'nan',
 'nan',
 'EKA4050052',
 'EUP3040004',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ETS4030013',
 'nan',
 'nan',
 'nan',
 'ETS4030013',
 'EGJ3050016',
 'nan',
 'EOD3010080',
 'nan',
 'nan',
 'EOD3010080',
 'nan',
 'nan',
 'nan',
 'nan',
 'EWB4020014',
 'nan',
 'ERJ4030107',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ERJ4030005',
 'nan',
 'EWB4020097',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EHR3010002',
 'EMP3010091',
 'nan',
 'nan',
 'nan',
 'EHR3010002',
 'nan',
 'nan',
 'nan',
 'nan',
 'ETN4010010',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EHR3010002',
 'nan',
 'EUP3040004',
 'EMH1040013',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH3020049',
 'nan',
 'nan',
 'nan',
 'nan',
 'EUP4030014',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EPB3020014',
 'nan',
 'nan',
 'EPB3010003',
 'EPB3010020',
 'EGJ4010021',
 'EPB3010020',
 'nan',
 'nan',
 'EPB3010020',
 'ERJ4030010',
 'ETN4010141',
 'EPB3010020',
 'nan',
 'ERJ4030010',
 'nan',
 'ERJ4030010',
 'nan',
 'nan',
 'EMH4040170',
 'nan',
 'nan',
 'nan',
 'nan',
 'EGJ4040012',
 'nan',
 'nan',
 'nan',
 'EMH1020052',
 'nan',
 'nan',
 'nan',
 'EWB4020015',
 'nan',
 'nan',
 'nan',
 'EKA3040010',
 'nan',
 'EKL3030062',
 'nan',
 'nan',
 'EUP3010006',
 'nan',
 'nan',
 'EUP3010006',
 'nan',
 'nan',
 'EGJ4030002',
 'nan',
 'nan',
 'nan',
 'nan',
 'EOD3010080',
 'nan',
 'nan',
 'EPB3010020',
 'nan',
 'EUP3010006',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ERJ4030107',
 'EDL4040133',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH1020052',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EGJ4010021',
 'EMH3020049',
 'nan',
 'nan',
 'EAP3040007',
 'nan',
 'EPB3010020',
 'nan',
 'nan',
 'nan',
 'ERJ4030005',
 'nan',
 'nan',
 'ERJ4030010',
 'nan',
 'nan',
 'EPB3010020',
 'EWB4020013',
 'nan',
 'EMH1020052',
 'EPB3010003',
 'nan',
 'nan',
 'EMP3030002',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EUP3010006',
 'EGJ3040104',
 'nan',
 'nan',
 'EWB4020013',
 'EPB3010003',
 'nan',
 'nan',
 'EMP3020023',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ECH4010003',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ETS4030013',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH4040003',
 'EMH4040003',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH4070004',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH4070004',
 'EWB4020097',
 'nan',
 'nan',
 'EMH3020049',
 'nan',
 'EWB4020013',
 'nan',
 'EAP3040004',
 'nan',
 'ECH4010003',
 'nan',
 'nan',
 'nan',
 'EKA3010170',
 'EKA3010092',
 'EAP3040007',
 'nan',
 'nan',
 'nan',
 'nan',
 'EKL3020137',
 'EKA4050088',
 'nan',
 'EMH1040005',
 'nan',
 'EMH4040170',
 'EMP3020054',
 'ETS4030013',
 'EMH1040005',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EHR4010061',
 'nan',
 'nan',
 'ERJ4010106',
 'nan',
 'nan',
 'EMH4070004',
 'nan',
 'EAP3040004',
 'nan',
 'nan',
 'EKL3020171',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EKA3010092',
 'nan',
 'nan',
 'EUP3040115',
 'nan',
 'EHR4050069',
 'nan',
 'nan',
 'EMH1040067',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EGJ3060001',
 'nan',
 'nan',
 'nan',
 'nan',
 'EDL4040133',
 'nan',
 'nan',
 'nan',
 'ECG3010015',
 'EMH4010017',
 'nan',
 'EMH4070004',
 'nan',
 'nan',
 'EKA4050052',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH3040008',
 'nan',
 'nan',
 'EGJ4040130',
 'EMH4070004',
 'nan',
 'EKL3020137',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EKA4010122',
 'nan',
 'nan',
 'nan',
 'EHP3010005',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH4040170',
 'nan',
 'nan',
 'nan',
 'nan',
 'EUP4030014',
 'nan',
 'nan',
 'EMH4010017',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ERJ4010003',
 'nan',
 'EGJ3060001',
 'ERJ4020001',
 'nan',
 'EUP3010006',
 'EOD3010080',
 'EKL3020137',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ETS4030013',
 'nan',
 'nan',
 'ETS4030013',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EGJ4040130',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EHR3010002',
 'nan',
 'nan',
 'EGJ3040104',
 'ERJ4010106',
 'nan',
 'nan',
 'EHR4050069',
 'nan',
 'nan',
 'nan',
 'EPB3010113',
 'EPB3010113',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EAP3040007',
 'nan',
 'EKL3040014',
 'nan',
 'EMH1040013',
 'nan',
 'EKA3010170',
 'EHP3010005',
 'EKL3030062',
 'nan',
 'nan',
 'EAS4010013',
 'EKL3020171',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EGJ3040104',
 'ERJ4010003',
 'nan',
 'ERJ4010106',
 'nan',
 'ERJ4010106',
 'nan',
 'nan',
 'EAP3040007',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH3040118',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EHR3020055',
 'EAS4010013',
 'EMH4010017',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH4060126',
 'nan',
 'nan',
 'EGJ3040104',
 'nan',
 'nan',
 'nan',
 'EUP4030263',
 'nan',
 'nan',
 'EHR4050069',
 'nan',
 'nan',
 'EPB3010009',
 'nan',
 'nan',
 'nan',
 'nan',
 'ETS4030013',
 'EKL3030062',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EAP3040007',
 'nan',
 'nan',
 'nan',
 'nan',
 'EGJ4030002',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'EMH4080154',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ECG3010015',
 'nan',
 'EHR3030049',
 'nan',
 'nan',
 'ECH4010003',
 'nan',
 'nan',
 'nan',
 'nan',
 ...]

In [15]:
df['Team_Leader_Code'] = Team_Leader_Code

In [16]:
df

,TEAM_LEADER,TEAM_LEADER_JOINING_DATE,TEAM_LEADER_LEAVE_DATE,KEC,KEC_NAME,KEC_CODE,KEC_JOIN_DATE,KEC_LEAVE_DATE,EQRY_ENQRY_NO,EQRY_DLR_NO,Team_Leader_Code
0,nan,NaN,NaN,EAP3020001,Aditya Soni,TRAP30220190001,2019-07-14,NaN,E201900003,TRAP302,nan
1,nan,NaN,NaN,EUP4030004,KASHISH SHARMA,TRUP40320190004,2019-07-10,1970-01-01 00:00:00.020210817,E201900001,TRUP403,nan
2,EUP4030014;VISHAL SHARMA;Active,2019-07-14,NaN,EUP4030002,HIMANSHU MITTAL,TRUP40320190002,2019-07-10,NaN,E201900003,TRUP403,EUP4030014
3,nan,NaN,NaN,EUP4030001,RANJANA SAXENA,TRUP40320190001,2019-07-10,NaN,E201900006,TRUP403,nan
4,nan,NaN,NaN,EUP4030001,RANJANA SAXENA,TRUP40320190001,2019-07-10,NaN,E201900007,TRUP403,nan
...,...,...,...,...,...,...,...,...,...,...,...
3436392,nan,NaN,NaN,EKA5020055,MUSTAFA S MULLA,TRKA50220210030,2021-09-14,NaN,E202201318,TRKA502,nan
3436393,ERJ3020004;Mohit Sharma;Active,2021-02-11,NaN,ERJ3020012,REKHA JAIN,TRRJ30220210003,2021-02-11,NaN,E202205715,TRRJ302,ERJ3020004
3436394,EPB1010017;RAJBIR SINGH;Active,2019-10-11,NaN,EPB1010034,ANKUR SETHI,TRPB10120200012,2020-02-22,NaN,E202203370,TRPB101,EPB1010017
3436395,EMH4100076;LAXMIKANT RAMSIRJAN PANDEY;Active,2020-08-18,NaN,EMH4100089,RAVIKANT RAJESH MISHRA,TR,2020-11-10,NaN,E202207685,TRMH410,EMH4100076
3436396,EMH4050061;Amol Chandrakant Chavan;Active,2020-08-01,NaN,EMH4050029,Reshma Pralhad Channe,TRMH40520190006,2019-12-20,NaN,E202207084,TRMH405,EMH4050061

In [17]:
for i in df['TEAM_LEADER']:
    x = i.split(';')
    if len(x) == 1:
        y = x[0]
        Team_Leader_Name.append(y)
    else:
        z = x[1]
        Team_Leader_Name.append(z.upper())

In [18]:
Team_Leader_Name

['nan',
 'nan',
 'VISHAL SHARMA',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ASHWIN BELTHUR M',
 'CHETHAN R',
 'nan',
 'nan',
 'ABHINAV DINTAKURTHI',
 'PAILA GOPI KRISHNA',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'AMIT UKIL',
 'nan',
 'nan',
 'SANJAY MOTIRAM MUNGE ',
 'RANJITH J',
 'HIMMAT SINGH',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SANJAY MOTIRAM MUNGE ',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SANJAY MOTIRAM MUNGE ',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'JITHIN S',
 'nan',
 'nan',
 'SANJAY MOTIRAM MUNGE ',
 'CHETHAN R',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'HARDIK HINGU',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'RAJSHRI PATARE',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SANJAY MOTIRAM MUNGE ',
 'nan',
 'nan',
 'SAQIB KHAN',
 'nan',
 'nan',
 'HIMMAT SINGH',
 'nan',
 'nan',
 'HARDIK HINGU',
 'nan',
 'ABHISHEK TRIPATHI',
 'HIMMAT SINGH',
 'nan',
 'SUVADEEP BHATTACHARYA',
 'UPENDRA SAHU',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ZUBER MIRZA',
 'nan',
 'KARUNESH GARG',
 'nan',
 'nan',
 'HARDIK HINGU',
 'VIJAY GURJAR',
 'PARVEEN UPPAL',
 'nan',
 'KARUNESH GARG',
 'PINAK SHARMA',
 'nan',
 'HIMMAT SINGH',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'DEEPAK KUMAR BHUYAN',
 'nan',
 'MANOJ CHAUDHARY',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'DEEPAK KUMAR BHUYAN',
 'nan',
 'nan',
 'nan',
 'SARADA PRASAN DASH',
 'nan',
 'nan',
 'DEEPAK KUMAR BHUYAN',
 'ASHISH KUMAR',
 'nan',
 'SANJAY MOTIRAM MUNGE ',
 'nan',
 'KARUNESH GARG',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'J VINODH',
 'nan',
 'nan',
 'nan',
 'KARUNESH GARG',
 'ASHOK TATWAVEDI',
 'nan',
 'BIJENDER',
 'nan',
 'SAQIB KHAN',
 'nan',
 'nan',
 'nan',
 'nan',
 'ASHWIN BELTHUR M',
 'ASHWIN BELTHUR M',
 'ASHWIN BELTHUR M',
 'nan',
 'nan',
 'nan',
 'CHETHAN R',
 'CHETHAN R',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ASHOK TATWAVEDI',
 'HIMMAT SINGH',
 'nan',
 'nan',
 'nan',
 'nan',
 'HAREESH THIRUNILATHIL SASI',
 'nan',
 'HAREESH THIRUNILATHIL SASI',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'HARPREET SINGH',
 'nan',
 'MANISH TANK',
 'NIRANJAN KATARIYA',
 'GAURAV BHADAURIYA',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ASHWIN BELTHUR M',
 'nan',
 'nan',
 'nan',
 'nan',
 'SANJAY MOTIRAM MUNGE ',
 'CHETHAN R',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SACHIN GUPTA ',
 'nan',
 'HIMMAT SINGH',
 'KAPIL SINGH ',
 'HIMMAT SINGH',
 'CHETHAN R',
 'nan',
 'JITHIN S',
 'nan',
 'HARDIK HINGU',
 'nan',
 'SARADA PRASAN DASH',
 'HAREESH THIRUNILATHIL SASI',
 'nan',
 'PRAJESH D JOSHI',
 'HAREESH THIRUNILATHIL SASI',
 'nan',
 'nan',
 'nan',
 'E DHAMODHAR\t',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SACHIN GUPTA ',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SUSHMA VARUNA M',
 'nan',
 'nan',
 'SOHEL KHAN',
 'nan',
 'NITIN SHARMA',
 'ARSHAD',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'VISHAL SHARMA',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ANKIT SHARMA',
 'ANKIT SHARMA',
 'MONALISA BHATTACHARJEE',
 'nan',
 'VIJAY SHARMA',
 'nan',
 'MAHESH SAINI',
 'SUSHMA VARUNA M',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'VISHAL SHARMA',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'HIRAK JYOTI GOGOI',
 'DEEPAK KUMAR SINGH',
 'nan',
 'nan',
 'THIRUMALAIAPPAN V  T',
 'PULKIT AGGARWAL',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ABHINAV DINTAKURTHI',
 'LOURDUSAMY A',
 'nan',
 'ABHINAV DINTAKURTHI',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'DHIRAJ DATTATRAY KULKARNI',
 'nan',
 'nan',
 'ABHINAV DINTAKURTHI',
 'nan',
 'nan',
 'nan',
 'E DHAMODHAR\t',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SAIRAMA SK',
 'SOHEL KHAN',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'J VINODH',
 'nan',
 'nan',
 'nan',
 'nan',
 'DHIRAJ DATTATRAY KULKARNI',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SUSHMA VARUNA M',
 'nan',
 'nan',
 'nan',
 'PAILA GOPI KRISHNA',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'MANOJ CHAUDHARY',
 'SUSHANT RAJARAM BODKE',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ASHWIN BELTHUR M',
 'nan',
 'B SRINIVASARAO',
 'HAREESH THIRUNILATHIL SASI',
 'nan',
 'nan',
 'RAJSHRI PATARE',
 'nan',
 'SOHEL KHAN',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SANJAY MOTIRAM MUNGE ',
 'nan',
 'HIRAK JYOTI GOGOI',
 'nan',
 'nan',
 'nan',
 'nan',
 'MONALISA BHATTACHARJEE',
 'SANJAY MOTIRAM MUNGE ',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'HIRAK JYOTI GOGOI',
 'nan',
 'nan',
 'nan',
 'nan',
 'MONALISA BHATTACHARJEE',
 'nan',
 'nan',
 'nan',
 'DEEPAK KUMAR BHUYAN',
 'nan',
 'nan',
 'nan',
 'nan',
 'CHETHAN R',
 'ANKIT SHARMA',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ABHINAV DINTAKURTHI',
 'nan',
 'nan',
 'nan',
 'ABHINAV DINTAKURTHI',
 'PRAJESH D JOSHI',
 'nan',
 'DEEPAK KUMAR BHUYAN',
 'nan',
 'nan',
 'DEEPAK KUMAR BHUYAN',
 'nan',
 'nan',
 'nan',
 'nan',
 'SOUNANDA SEN',
 'nan',
 'HIMMAT SINGH',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'MANVENDRA SINGH PANWAR',
 'nan',
 'AMIT UKIL',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'BIJENDER',
 'ARSHAD',
 'nan',
 'nan',
 'nan',
 'BIJENDER',
 'nan',
 'nan',
 'nan',
 'nan',
 'REVATHI C',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'BIJENDER',
 'nan',
 'ANKIT SHARMA',
 'DHIRAJ DATTATRAY KULKARNI',
 'nan',
 'nan',
 'nan',
 'nan',
 'SANJAY MOTIRAM MUNGE ',
 'nan',
 'nan',
 'nan',
 'nan',
 'VISHAL SHARMA',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ANIMESH SHARMA',
 'nan',
 'nan',
 'NITIN SHARMA',
 'HARPREET SINGH',
 'GAURAV BHADAURIYA',
 'HARPREET SINGH',
 'nan',
 'nan',
 'HARPREET SINGH',
 'VIJAY GURJAR',
 'LOURDUSAMY A',
 'HARPREET SINGH',
 'nan',
 'VIJAY GURJAR',
 'nan',
 'VIJAY GURJAR',
 'nan',
 'nan',
 'AMIT MOHANKANT KHAPARDE ',
 'nan',
 'nan',
 'nan',
 'nan',
 'BHAVIN VIJAYBHAI DESAI',
 'nan',
 'nan',
 'nan',
 'VIVEK BABHARE',
 'nan',
 'nan',
 'nan',
 'MONALISA BHATTACHARJEE',
 'nan',
 'nan',
 'nan',
 'CHANDAN',
 'nan',
 'HAREESH THIRUNILATHIL SASI',
 'nan',
 'nan',
 'KARUNESH GARG',
 'nan',
 'nan',
 'KARUNESH GARG',
 'nan',
 'nan',
 'HIREN ARIWALA',
 'nan',
 'nan',
 'nan',
 'nan',
 'DEEPAK KUMAR BHUYAN',
 'nan',
 'nan',
 'HARPREET SINGH',
 'nan',
 'KARUNESH GARG',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'HIMMAT SINGH',
 'SAQIB KHAN',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'VIVEK BABHARE',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'GAURAV BHADAURIYA',
 'SANJAY MOTIRAM MUNGE ',
 'nan',
 'nan',
 'E DHAMODHAR\t',
 'nan',
 'HARPREET SINGH',
 'nan',
 'nan',
 'nan',
 'MANVENDRA SINGH PANWAR',
 'nan',
 'nan',
 'VIJAY GURJAR',
 'nan',
 'nan',
 'HARPREET SINGH',
 'SUVADEEP BHATTACHARYA',
 'nan',
 'VIVEK BABHARE',
 'NITIN SHARMA',
 'nan',
 'nan',
 'ABHISHEK DIXIT',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'KARUNESH GARG',
 'HARDIK HINGU',
 'nan',
 'nan',
 'SUVADEEP BHATTACHARYA',
 'NITIN SHARMA',
 'nan',
 'nan',
 'RAHUL GOLE',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'KUNAL MAGGU',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ABHINAV DINTAKURTHI',
 'nan',
 'nan',
 'nan',
 'nan',
 'SUNIL\xa0\xa0 NAGPURE',
 'SUNIL\xa0\xa0 NAGPURE',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ROHIT RAVINDRA KORE',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ROHIT RAVINDRA KORE',
 'AMIT UKIL',
 'nan',
 'nan',
 'SANJAY MOTIRAM MUNGE ',
 'nan',
 'SUVADEEP BHATTACHARYA',
 'nan',
 'J VINODH',
 'nan',
 'KUNAL MAGGU',
 'nan',
 'nan',
 'nan',
 'L SANTHOSH KUMAR',
 'SAMPATH',
 'E DHAMODHAR\t',
 'nan',
 'nan',
 'nan',
 'nan',
 'SIRIL R S',
 'ASHWIN BELTHUR M',
 'nan',
 'SATYAJEET CHANDRAKANT KAPSE',
 'nan',
 'AMIT MOHANKANT KHAPARDE ',
 'GYANESHWAR SINGH',
 'ABHINAV DINTAKURTHI',
 'SATYAJEET CHANDRAKANT KAPSE',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'MAHESH SAINI',
 'nan',
 'nan',
 'ASHOK TATWAVEDI',
 'nan',
 'nan',
 'ROHIT RAVINDRA KORE',
 'nan',
 'J VINODH',
 'nan',
 'nan',
 'SINOY K JOSEPH',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SAMPATH',
 'nan',
 'nan',
 'MANOJ CHAUDHARY',
 'nan',
 'PULKIT AGGARWAL',
 'nan',
 'nan',
 'SHIVANAND REVANSIDDHA CHOLLE',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ZUBER MIRZA',
 'nan',
 'nan',
 'nan',
 'nan',
 'SAQIB KHAN',
 'nan',
 'nan',
 'nan',
 'UPENDRA SAHU',
 'RAJSHRI PATARE',
 'nan',
 'ROHIT RAVINDRA KORE',
 'nan',
 'nan',
 'CHETHAN R',
 'nan',
 'nan',
 'nan',
 'nan',
 'KUMAR VITTHAL KIWADI',
 'nan',
 'nan',
 'SANDIP WANKHEDE',
 'ROHIT RAVINDRA KORE',
 'nan',
 'SIRIL R S',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SUSHMA VARUNA M',
 'nan',
 'nan',
 'nan',
 'SHASHI KANT',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'AMIT MOHANKANT KHAPARDE ',
 'nan',
 'nan',
 'nan',
 'nan',
 'VISHAL SHARMA',
 'nan',
 'nan',
 'RAJSHRI PATARE',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ASHISH KUMAR',
 'nan',
 'ZUBER MIRZA',
 'ABHISHEK TRIPATHI',
 'nan',
 'KARUNESH GARG',
 'DEEPAK KUMAR BHUYAN',
 'SIRIL R S',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'ABHINAV DINTAKURTHI',
 'nan',
 'nan',
 'ABHINAV DINTAKURTHI',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SANDIP WANKHEDE',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'BIJENDER',
 'nan',
 'nan',
 'HARDIK HINGU',
 'ASHOK TATWAVEDI',
 'nan',
 'nan',
 'PULKIT AGGARWAL',
 'nan',
 'nan',
 'nan',
 'SOURABH BHATIA',
 'SOURABH BHATIA',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'E DHAMODHAR\t',
 'nan',
 'JITHIN S',
 'nan',
 'DHIRAJ DATTATRAY KULKARNI',
 'nan',
 'L SANTHOSH KUMAR',
 'SHASHI KANT',
 'HAREESH THIRUNILATHIL SASI',
 'nan',
 'nan',
 'PRASENJIT MAJUMDER',
 'SINOY K JOSEPH',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'HARDIK HINGU',
 'ASHISH KUMAR',
 'nan',
 'ASHOK TATWAVEDI',
 'nan',
 'ASHOK TATWAVEDI',
 'nan',
 'nan',
 'E DHAMODHAR\t',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SANJAY VIJAY BHOSALE',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SACHIN RANA',
 'PRASENJIT MAJUMDER',
 'RAJSHRI PATARE',
 'nan',
 'nan',
 'nan',
 'nan',
 'ROHAN MALI',
 'nan',
 'nan',
 'HARDIK HINGU',
 'nan',
 'nan',
 'nan',
 'MANISH SHARMA',
 'nan',
 'nan',
 'PULKIT AGGARWAL',
 'nan',
 'nan',
 'PARVEEN UPPAL',
 'nan',
 'nan',
 'nan',
 'nan',
 'ABHINAV DINTAKURTHI',
 'HAREESH THIRUNILATHIL SASI',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'E DHAMODHAR\t',
 'nan',
 'nan',
 'nan',
 'nan',
 'HIREN ARIWALA',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'SHYAM LAXMAN BODKE ',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'UPENDRA SAHU',
 'nan',
 'GAGAN KUMAR',
 'nan',
 'nan',
 'KUNAL MAGGU',
 'nan',
 'nan',
 'nan',
 'nan',
 ...]

In [19]:
df['Team_Leader_Name'] = Team_Leader_Name

In [20]:
for i in df['TEAM_LEADER']:
    x = i.split(';')
    if len(x) == 1:
        y = x[0]
        Active_Inactive.append(y)
    else:
        z = x[2]
        Active_Inactive.append(z.upper())

In [21]:
df['Active_Inactive'] = Active_Inactive

In [22]:
df.rename(columns = {'KEC':'KEC_Short_Code'}, inplace = True)

In [23]:
df['KEC'] = df['KEC_NAME'].str.upper()

In [24]:
df.rename(columns = {'KEC_CODE':'KEC_Long_Code'}, inplace = True)

In [25]:
df.rename(columns = {'TEAM_LEADER_LEAVE_DATE':'Team_leader_Leave_Date'}, inplace = True)

In [26]:
df.rename(columns = {'KEC_JOIN_DATE':'KEC_Join_Date'}, inplace = True)

In [27]:
df.rename(columns = {'KEC_LEAVE_DATE':'KEC_Leave_Date'}, inplace = True)

In [28]:
df.rename(columns = {'TEAM_LEADER_JOINING_DATE':'Team_leader_Joining_Date'}, inplace = True)

In [29]:
df.rename(columns = {'EQRY_ENQRY_NO':'Link_Enquiry_No'}, inplace = True)

In [30]:
df.rename(columns = {'EQRY_DLR_NO':'Dealer_No'}, inplace = True)

In [31]:
df.rename(columns = {'Active_Inactive':'Active/Inactive'}, inplace = True)

In [32]:
df

,TEAM_LEADER,Team_leader_Joining_Date,Team_leader_Leave_Date,KEC_Short_Code,KEC_NAME,KEC_Long_Code,KEC_Join_Date,KEC_Leave_Date,Link_Enquiry_No,Dealer_No,Team_Leader_Code,Team_Leader_Name,Active/Inactive,KEC
0,nan,NaN,NaN,EAP3020001,Aditya Soni,TRAP30220190001,2019-07-14,NaN,E201900003,TRAP302,nan,nan,nan,ADITYA SONI
1,nan,NaN,NaN,EUP4030004,KASHISH SHARMA,TRUP40320190004,2019-07-10,1970-01-01 00:00:00.020210817,E201900001,TRUP403,nan,nan,nan,KASHISH SHARMA
2,EUP4030014;VISHAL SHARMA;Active,2019-07-14,NaN,EUP4030002,HIMANSHU MITTAL,TRUP40320190002,2019-07-10,NaN,E201900003,TRUP403,EUP4030014,VISHAL SHARMA,ACTIVE,HIMANSHU MITTAL
3,nan,NaN,NaN,EUP4030001,RANJANA SAXENA,TRUP40320190001,2019-07-10,NaN,E201900006,TRUP403,nan,nan,nan,RANJANA SAXENA
4,nan,NaN,NaN,EUP4030001,RANJANA SAXENA,TRUP40320190001,2019-07-10,NaN,E201900007,TRUP403,nan,nan,nan,RANJANA SAXENA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3436392,nan,NaN,NaN,EKA5020055,MUSTAFA S MULLA,TRKA50220210030,2021-09-14,NaN,E202201318,TRKA502,nan,nan,nan,MUSTAFA S MULLA
3436393,ERJ3020004;Mohit Sharma;Active,2021-02-11,NaN,ERJ3020012,REKHA JAIN,TRRJ30220210003,2021-02-11,NaN,E202205715,TRRJ302,ERJ3020004,MOHIT SHARMA,ACTIVE,REKHA JAIN
3436394,EPB1010017;RAJBIR SINGH;Active,2019-10-11,NaN,EPB1010034,ANKUR SETHI,TRPB10120200012,2020-02-22,NaN,E202203370,TRPB101,EPB1010017,RAJBIR SINGH,ACTIVE,ANKUR SETHI
3436395,EMH4100076;LAXMIKANT RAMSIRJAN PANDEY;Active,2020-08-18,NaN,EMH4100089,RAVIKANT RAJESH MISHRA,TR,2020-11-10,NaN,E202207685,TRMH410,EMH4100076,LAXMIKANT RAMSIRJAN PANDEY,ACTIVE,RAVIKANT RAJESH MISHRA
3436396,EMH4050061;Amol Chandrakant Chavan;Active,2020-08-01,NaN,EMH4050029,Reshma Pralhad Channe,TRMH40520190006,2019-12-20,NaN,E202207084,TRMH405,EMH4050061,AMOL CHANDRAKANT CHAVAN,ACTIVE,RESHMA PRALHAD CHANNE

In [33]:
# df.to_csv("C:\\Users\\15442\\Desktop\\Files\\ETL Through Code\\Modified files\\Sales_Team_Leader(m).csv",index=False)